In [1]:
import numpy as np

tạo numpy arrays từ python lists

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

Python cho phép các item của list khác kiểu dữ liệu nhưng numpy thì không. Nó sẽ convert tất cả số nguyên thành float(thực)

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Điểm khác tiếp theo của python list và numpy array

numpy arrays có thể convert chuỗi số thành kiểu mình muốn. vd: chuyển sang kiểu số thực 32bit

In [4]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

gán

In [5]:
a1 = np.array([1,2,3,4])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],
               [4,5,6]])

In [8]:
type(a2)

numpy.ndarray

In [9]:
a2.shape # mấy cột mấy dòng

(2, 3)

In [10]:
a2.dtype # kiểu dữ liệu

dtype('int64')

In [11]:
a2.size # tổng số phần tử

6

# Createing numpy arrays from scratch

các hàm có sẵn của numpy: zeros, ones, full, arange, linspace

muốn biết các hàm cần input gì thì shift tab

In [12]:
np.zeros([2,4]) # tạo mảng toàn số 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros([2,4], dtype = int) # tạo mảng toàn số 0 kiểu int

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
np.ones((3, 5), dtype = float) # tạo mảng toàn số 1 kiểu float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.arange(0, 20, 2) # tạo mảng từ 0 đến 20 với bước nhảy là 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.full((3, 5), 6.9) # tạo mảng toàn số 6.9

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [23]:
np.linspace(0, 1, 5) # tạo mảng từ 0 đến 1 với 5 số

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [24]:
np.random.random((4, 4)) # tạo mảng ngẫu nhiên 4 hàng 4 cột số ngẫu nhiêu từ 0-1

array([[0.198169  , 0.44547468, 0.54557187, 0.05756874],
       [0.59637923, 0.78937159, 0.41247918, 0.60958086],
       [0.63783276, 0.19119565, 0.84360608, 0.14639102],
       [0.02686198, 0.49082358, 0.11159086, 0.5118699 ]])

In [25]:
#seed: random nhưng ra số giống nhau ở các máy
np.random.seed(0)
np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [28]:
np.random.rand(4,4) # tạo mảng ngẫu nhiên 4 hàng 4 cột số ngẫu nhiêu từ 0-1. K cần mở ngoặc đóng ngoặc

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

In [26]:
np.random.normal(0, 1, (3, 3)) # tạo mảng ngẫu nhiên có mean(giá trị tbinh) = 0, std(độ lệch chuẩn) = 1; size 3x3

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [27]:
np.random.randint(0, 10, (4, 5)) # tạo mảng ngẫu nhiên integer có giá trị ngẫu nhiên từ low:0-high:10; size(shape) 4x5. k bao gồm số 10

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

# Array indexing & Slicing

one-dimensional subarray

In [29]:
x1 = np.random.randint(20, size = 6) # tạo mảng ngẫu nhiên integer có giá trị ngẫu nhiên từ low:0-high:20; size(shape) 6

In [30]:
x1

array([15, 13, 16, 17,  5,  9])

In [31]:
x1[4] # lấy phần tử thứ 4

5

In [32]:
x1[4], x1[0], x1[-1] # lấy phần tử thứ 4, đầu tiên, cuối

(5, 15, 9)

Multi-dimension array

In [33]:
x2 = np.random.randint(10, size = (3, 4)) # tạo mảng ngẫu nhiên integer có giá trị ngẫu nhiên từ low:0-high:10; size(shape) 3x4

In [34]:
x2

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [35]:
x2[1, 2] # lấy phần tử hàng 1 cột 2.( lưu ý đếm từ 0 cả row lẫn column)

4

In [36]:
x2[1, 2] = 6 # gán giá trị cho phần tử hàng 1 cột 2

In [37]:
x2

array([[3, 0, 5, 0],
       [1, 2, 6, 2],
       [0, 3, 2, 0]])

Slicing: cắt

x[start:stop:step]

In [38]:
x1

array([15, 13, 16, 17,  5,  9])

In [39]:
x1[0:3] # lấy phần tử từ 0 đến 2, k lấy 3 (lấy 3 giá trị đầu tiên)

array([15, 13, 16])

In [40]:
x1[2:4] # lấy phần tử từ 2 đến 3, k lấy 4 (lấy 2 giá trị giữa)

array([16, 17])

In [41]:
x1[::2] # lấy phần tử từ đầu đến cuối, bước nhảy là 2

array([15, 16,  5])

In [42]:
x2

array([[3, 0, 5, 0],
       [1, 2, 6, 2],
       [0, 3, 2, 0]])

In [43]:
x2[:2, :3] # lấy 2 hàng đầu tiên, 3 cột đầu tiên
# trước dấu phẩy là row, sau phẩy là column

array([[3, 0, 5],
       [1, 2, 6]])

In [45]:
x2[:, :2] # lấy tất cả hàng, 2 cột đầu tiên

array([[3, 0],
       [1, 2],
       [0, 3]])

# Reshaping of Arrays & Transpose

thay đổi shape của array

In [46]:
grib = np.arange(1, 10) # tạo mảng từ 1 đến 9
grib.shape

(9,)

In [48]:
grib.reshape((3, 3)) # thay đổi shape của array thành ma trận 3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
x = np.array([1, 2, 3])
x.reshape((1, 3)).shape # reshape thành ma trận 1x3

(1, 3)

reshape là thay đổi thành theo ý. Transpose là convert từ hàng thành cột, cột thành hàng

In [53]:
x = np.array([[1., 2.], [3., 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [55]:
x.T # chuyển vị

array([[1., 3.],
       [2., 4.]])

# Array Concatenation and Splitting

nối array và tách array thành các arr nhỏ

In [56]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [57]:
np.concatenate((x, y)) # nối 2 array x và array y

array([1, 2, 3, 3, 2, 1])

In [59]:
grib = np.array([[1, 2, 3],
                [4, 5, 6]])
grib

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.concatenate((grib, grib)) # nối 2 array grib và grib
# mặc định axis = 0. Nối theo trục row dọc

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate((grib, grib), axis = 1) # nối 2 array grib và grib theo hướng column. ngang

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
# vstack
x = np.array([1, 2, 3])
grib = np.array([[9, 8, 7],
               [6, 5, 4]])

In [63]:
np.vstack((x, grib)) # nối theo trục row dọc

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [64]:
# Horizontally stack
y = np.array([[99],
             [99]])
np.hstack((y, grib)) # nối theo trục column ngang


array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

Splitting of arrays

In [65]:
x = np.array([1, 2, 3, 99, 69, 3, 2, 1])

In [66]:
# iput array muốn split. khoảng muốn tách
x1, x2, x3 = np.split(x, [3, 5]) # tách array thành 3 array con và gán


In [67]:
x1

array([1, 2, 3])

In [68]:
x2

array([99, 69])

In [70]:
x3

array([3, 2, 1])

# Broadcasting and Vectorized operations

broadcasting để cùng size(shape) các mảng để cộng được với nhau

In [71]:
a = np.arange(3)
a

array([0, 1, 2])

In [72]:
a + 5 # cộng a (Broadcasting)
# tự broadcasting thành (5, 5, 5) để cộng

array([5, 6, 7])

In [73]:
b = np.ones((3, 3))
b # mảng b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
a.shape, b.shape # mảng 1 chiều và mảng 3x3

((3,), (3, 3))

In [75]:
a + b
# broadcasting array a thành (0,1,2
#                             0,1,2
#                             0,1,2)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [76]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [77]:
c = np.arange(3).reshape((3, 1))
c

array([[0],
       [1],
       [2]])

In [78]:
a

array([0, 1, 2])

In [79]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating & Comparing Arrays

In [80]:
# Aggregation
list_number = [1, 2, 3]

In [81]:
ll = np.array(list_number)
ll

array([1, 2, 3])

In [82]:
sum(ll) # hàm sum của python

6

In [83]:
np.sum(ll) # hàm sum của numpy

6

In [84]:
# Create a massive Numpy array: tạo 1 array rất lớn
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [85]:
# %timeit return thời gian tính của phép ở sau
%timeit sum(massive_array) # python sum
%timeit np.sum(massive_array) # numpy sum nhanh hơn rất nhiều

2.5 ms ± 588 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
6.96 µs ± 226 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [86]:
np.mean(massive_array) # giá trị trung bình

0.49644077223750666

In [87]:
np.max(massive_array) # giá trị lớn nhất

0.9999779517807228

In [88]:
np.min(massive_array) # giá trị nhỏ nhất
#

7.2449638492178e-05

# Statistics: xác xuất thống kê

mean: giá trị tbinh

variance: phương sai (CT: lấy tổng độ lệch chuẩn từng con (giá trị từng con - mean) bình phương lên và chia trung bình)

Standard Deviation: độ lệch chuẩn +- để biết dữ liệu nào là normal, extra large or extra small (CT: square root of Variance (căn bậc 2 phương sai))

In [89]:
dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)
np.std(dog_height) # độ lệch chuẩn

147.32277488562318

In [90]:
np.var(dog_height) # phương sai

21704.0

In [91]:
np.sqrt(np.var(dog_height)) # căn bậc 2 của phương sai-> độ lệch chuẩn standard deviation

147.32277488562318

# Sorting arrays

np.sort dùng thuật toán quicksort

In [92]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [93]:
np.argsort(x) # trả về index của các phần tử đã sort

array([1, 0, 3, 2, 4])

Sorting along rows or columns

In [94]:
np.random.seed(42)
MatA = np.random.randint(0, 10, size = (4, 6))

In [95]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [96]:
np.sort(MatA, axis = 0) # sort theo cột columns

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [97]:
np.sort(MatA, axis = 1) # sort theo hàng rows

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Linear Algebra: đại số tuyến tính

In [98]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

In [99]:
B = np.array([[6, 5],
             [4, 3],
             [2, 1]])

In [100]:
# (3x3) dot product (3x2) : tích vô hướng
# hàng đầu tiên của A nhân với cột đầu tiên của B: 1x6 + 2x4 + 3x2 = 20
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [101]:
# hoặc cách khác để tính tích vô hướng
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [102]:
# để dot(tích vô hướng) thì hàng ngang đầu tiên của A nhân cột đầu tiên của B. Là 2 cái đó = số lượng
# B (3x2) dot A (3x3): k thể
B.T # (2x3) dot A(3x3): có thể

array([[6, 4, 2],
       [5, 3, 1]])

In [103]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

vd về dot product

In [104]:
# number of jars sold
np.random.seed(0)
sales_amounts = np.random.randint(20, size = (5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [105]:
# create weekly_sales dataframe
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns = ["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [106]:
# create a price array
prices = np.array([10, 8, 12])


In [107]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), index = ["Price"], columns = ["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [108]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [109]:
total_prices = weekly_sales.dot(butter_prices.T)
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [110]:
weekly_sales["Total prices"] = total_prices
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total prices
Mon               12             15              0           240
Tues               3              3              7           138
Wed                9             19             18           458
Thurs              4              6             12           232
Fri                1              6              7           142